### ISSUE TITLE
no sound at all except for boot sound after running nobootsound

### ISSUE THREAD

**Issue by GDSA01** [teored90/nobootsound#1]
After running Teo's script as shown on site:

https://github.com/teored90/nobootsound/blob/master/install.sh

I found that the ONLY sound I had on my macbook Pro (17" A1261 w/Yosemite 10.10.3) was the boot sound. All other sounds are missing; sound icon is greyed out in menu bar and "internal speakers" option is absent from SysPref sound window. I tried to uninstall with
 "sudo sh install.sh -u", but got
"sh: install.sh: No such file or directory"

Presumably I did something wrong at install and if Teo or someone else could offer any helpful suggestions I would greatly appreciate it.

Also does anyone know how to email Teo direct? Don't have a ny idea as to how often he checks these Issues.

GDSA01

**Comment by matteoacrossi** [comment]
I seriously doubt that this script can make the speakers disappear from the preferences sound panel. The only commands that are executed are the Applescript `set volume with/without output muted` which toggle the mute state of the audio output. No low-level hacks are involved. 

I suggest you restart the computer, try to plug / unplug earphones or Google for possible solutions (such as a PRAM reset).

As for the uninstallation, please manually remove the login and logout hooks by running the commands

```
sudo defaults delete com.apple.loginwindow LoginHook
sudo defaults delete com.apple.loginwindow LogoutHook
```

in a Terminal, and then remove the files

```
rm ~/.nobootsound_loginhook
rm ~/.nobootsound_logouthook
rm ~/.nobootsound_logoutvol
```

If a `No such file or directory` error is thrown, it means that the files are not there, so the script was not installed or already removed.

Please let me know if the problem with the internal speakers is solved. If now, we can look for other possible solutions.

**Comment by GDSA01** [comment]
Thanks for the rapid response - very decent of you, and please be clear, I'm not suggesting that your script is at fault.

I've tried the PRAM reset - no change. Plugging in the headset works fine - headset appears and disappears on removal from the SysPref audio pane.
I tried running your first 2 suggested scripts with the following results:

Last login: Sat Jun 20 15:31:21 on console
mbp:~ Graham$ sudo defaults delete com.apple.loginwindow LoginHook
Password:
2015-06-20 15:37:25.152 defaults[491:8629] 
Domain (com.apple.loginwindow) not found.
Defaults have not been changed.
mbp:~ Graham$ sudo defaults delete com.apple.loginwindow LogoutHook
2015-06-20 15:38:02.029 defaults[493:8813] 
Domain (com.apple.loginwindow) not found.
Defaults have not been changed.
mbp:~ Graham$ 

I googled on "domain (com.apple.loginwindow) not found" & found quite a bit on the subject but little of it comprehensible to me.

I also tried the first remove command and got:

mbp:~ Graham$ rm ~/.nobootsound_loginhook
rm: /Users/Graham/.nobootsound_loginhook: No such file or directory
mbp:~ Graham$ rm ~/.nobootsound_loginhook

...so I take it from your comments that that means that the script was not installed. Rum, because the audio blackout occurred right after I ran the script _ I'v tried recovering the script line by line to show you but the up arrow only seems to go so far upstream.

Hope this may help you help me recover from the blackout.

Thanks for your time.

**Comment by matteoacrossi** [comment]
The outputs of the commands that you executed show that the script was not installed (or that you removed it when running `install.sh -u`, even if it gave an error message).

So now let's troubleshoot the problem with the audio. First of all, a Google search ("internal speakers missing", "audio icon greyed out") shows that it is a common problem, but the solutions are very diverse. 

Do you have any device connected to the computer? External displays or adapters, USB / Thunderbolt devices, paired bluetooth devices etc.? I suggest you disconnect all, turn bluetooth off and restart the computer.

If this doesn't help, you can try with the command

```
sudo killall coreaudiod
```

and then check in the preference pane if the internal speakers appear again. Also, open the Console and look for related error messages around the time at which you entered the command.

I've also found this http://hasin.me/2013/11/04/fix-grey-sound-icon-in-the-mac-os-x/. It contains commands which I don't know (they don't seem very harmful though), so you can try it at your own risk.

Finally, if you have a Time Machine backup, you may want to consider restoring the system to a previous snapshot.

**Comment by GDSA01** [comment]
Many thanks Teo. Currenly I'm sans internet so have to work on my phone.
Will follow your suggestions & let you know how it pans out. Good of you to
take the trouble.

Thanks & regards,
Graham Stagg
239.776.0500

**Comment by GDSA01** [comment]
Found this in Stack Exchange and my headset jack recepticle is definitely
emitting a red light so I take it the recept. is buggered in some way. Long
out of warranty so will attempt to clean.
Thanks for your help.

"Try picking up some compressed air 2 using it to blow out any dust or
debris that might be in the headphone jack. Make sure to first expel any
liquid build (white frost-like substance) before you spray in the headphone
jack.
You can also try fishing around in there (gently) with a ridiculously small
flathead screwdriver.
One question for you, is there a red light coming out of the headphone
jack? That's usually a bad sign that the audio jack thinks there's an
optical audio device plugged in (permanently.) If you're MacBook is under
warranty the Genius Bar will replace the Main Logic Board for free (or
about $300 if it is Out of Warranty.)
Otherwise, the simple and inexpensive Griffin iMic will provide USB audio
input & output."

Thanks & regards,
Graham Stagg
239.776.0500

**Comment by matteoacrossi** [comment]
I don't know much about the hardware of that generation of MacBooks. Newer MacBooks don't have optical outputs anymore. If the computer thinks that there is an optical cable plugged in, then you should probably see something in the Sound preference panel. It can be worth it to try and clean the plug.

**Comment by GDSA01** [comment]
Yes, Optical Digital-Out Port is the only option shown in the output device list. If I cure the problem I wl let you know; thanks much fr your help.

Thanks & regards,

Graham Stagg.
239-776-0500

**Comment by evalera** [comment]
I'm having the same problem: NO SOUND at all from my internal speakers after uninstalling your script.
My computer is a brand new iMac that worked like a charm.
Please HELP!!! :(

**Comment by matteoacrossi** [comment]
Do you have the same symptoms? I.e. grey sound icon? Which devices do you
see in the sound preferences panel?

Il giorno mer 24 giu 2015 15:41 evalera notifications@github.com ha
scritto:

**Comment by evalera** [comment]
Hi Teo,

Thank you SO MUCH for your quick response. I panicked a little when I found the problem but I'm happy to say I solved it (by pure luck)!

I have a new iMac that has a VERY loud startup chime. I did some research and noticed StartNinja doesn't work in iMac, so I decided to try your script.

Your script works very well! I didn't hear the start up chime when I started the computer this morning but when I tried to listen to some music there was no sound at all. I checked Settings -> Sounds and the Internal Speakers were still there as output, sound was not muted and I could change the "volume" with the keyboard and manually in settings. Everything was like it is supposed to be (no grey sound icon etc.), but no sound was coming out of the computer :(.
Then I decided to uninstall the script following your instructions. I restarted the computer and the startup chime came back, but not the sound when playing music or videos. Then is when I panicked hehe. Followed your instructions above and no files were found, so I knew the script was perfectly uninstalled.

How it was solved: I didn't know what else to try, so I randomly connected some wireless earphones I have lying around as sound output, and they worked! Then I decided to try plugging my (wired) earphones in and they worked as well. Then is when I tried the internal speakers again, and this time they worked!!! 

I'm not sure what the problem was, how I really solved it, or if this solution will still work while the script is installed. It seemed like the internal sound system was in a "fake" mute mode and it needed a "kick start"... (?)

Thank you again for your help, if I try the script again I will let you know what happens.

Best
Elvira.

**Comment by matteoacrossi** [comment]
Dear Elvira, I'm glad that you were able to solve the problem. It would be nice to understand why the script didn't work for you, but I think that the problem in your case is different than Graham's. I think that in your case the script muted the internal speakers but didn't unmute them after the startup. Maybe if you tried the script again you could help me in debugging the code. 

Beat regards,
Matteo

**Comment by evalera** [comment]
Dear Teo, I agree, my problem seems to be completely different to Graham's, I hope he can resolve his soon as well. 
I'm happy to say that I installed again your script and didn't have any problem with the sound anymore, so it seems that it was a one time glitch.
I will keep it installed and report back if there is any change. Thank you for the script, by the way! :)
Best,
Elvira.

**Comment by matteoacrossi** [comment]
Dear Elvira,

I'm glad that the script is working. Indeed, I'm quite confident that my script can't cause sound problems as it simply mutes / unmutes the audio using system commands.

Please let me know if you experience problems.

Kind regards,
Matteo Rossi
