### ISSUE TITLE
Doesn't work on El Capitan

### ISSUE THREAD

**Issue by themightyoarfish** [teored90/nobootsound#10]
I have an almost fresh/clean install of El Capitan, but the hooks don't seem to work. They run, but don't do anything

![screen shot 2016-07-14 at 11 08 42](https://cloud.githubusercontent.com/assets/11613312/16834281/6d1a9756-49b3-11e6-8f49-56ca7f7e61fa.png)

**Comment by matteoacrossi** [comment]
Are you using headphones or other external sound devices?

**Comment by themightyoarfish** [comment]
No, nothing.

**Comment by matteoacrossi** [comment]
This is odd. It is working correctly in my setup (El Capitan, script installed after the upgrade). I suggest you try to reinstall the script, making sure the install script is launched with `sudo`. If it doesn't work we can try to get more detailed logging.

**Comment by sasik-github** [comment]
It doesn't work when i did plug-in headphones, but without it works perfectly.
Do you have solution for headphones too?

**Comment by matteoacrossi** [comment]
Unfortunately, there is no solution to the problem with headphones because of how macOS manages audio devices.

**Comment by sasik-github** [comment]
Thank you very much for reply.
