### ISSUE TITLE
macOS Sierra supported?

### ISSUE THREAD

**Issue by s3frank** [teored90/nobootsound#11]
I just installed this follow the readme, rebooted my mac but now luck?
keeps playing that boot sound at the last known volume :-(

**Comment by matteoacrossi** [comment]
Dear s3franc,

I just did a clean install on a fresh macOS Sierra and the script is working as expected. So let's debug your problem.

Please check that the output of the three following commands is the same as the one reported below:

```
$ sudo defaults read com.apple.loginwindow LoginHook
/Library/LogHook/nobootsound_loginhook

$ sudo defaults read com.apple.loginwindow LogoutHook
/Library/LogHook/nobootsound_logouthook

$ ls /Library/LogHook/
nobootsound_loginhook*  nobootsound_logouthook* nobootsound_logoutvol
```

Thank you very much for your interest in the script!

**Comment by s3frank** [comment]
I'll do it next week as I'm traveling now

**Comment by s3frank** [comment]
Here's the output form your commands.
![screen shot 2016-10-13 at 23 12 38](https://cloud.githubusercontent.com/assets/2191242/19354834/b7256bd0-919a-11e6-9ede-134555b43c6f.png)

**Comment by s3frank** [comment]
BTW, I have permanently got a usb dect headset connected to the imac and some times a BT pair of headphones.

**Comment by matteoacrossi** [comment]
OK, then this explains the problem. Unfortunately, there doesn't seem to be a way to mute another sound device other than the one currently in use (in your case, the USB headset). But during boot the sound device is switched to the integrated speakers and thus the chime is played.
