### ISSUE TITLE
Modification to play a sound of selection

### ISSUE THREAD

**Issue by myppka** [teored90/nobootsound#16]
Hi,
Great job you've done!
I've got a very similar task that I've tried to do during the past few days and failed.
What I want to have is to have my personalised logon sound when I enter the password to my user account. For example when I open my MacBook, it awakes and I enter the password. This means that the computer was not shut down, so many of the options in web with "startup sounds" do not apply. Can you please help me with this?

**Comment by matteoacrossi** [comment]
Dear myppka, apparently it is not possible to change the boot sound. It is possible to add a login sound as reported here: https://apple.stackexchange.com/questions/224248/change-startup-bong-on-macbook-pro

This is however out of the scope of my script, so I am closing this issue.
