### ISSUE TITLE
Still have boot sound

### ISSUE THREAD

**Issue by meteormatt** [teored90/nobootsound#2]
Log is belog

``` bash
$ sudo sh install.sh 
Password:
stat: cannot read file system information for ‘%Su’: No such file or directory
Copying files...
sudo: unknown user: File:
sudo: unknown user: File:
sudo: unknown user: File:
sudo: unknown user: File:
sudo: unknown user: File:
sudo: unknown user: File:
Registering hooks...
Done!
```

Mac OS version: `10.10.4 (14E46)`

**Comment by albacoretuna** [comment]
Works on my 10.10.2 

$ sudo sh install.sh 
Password:
Copying files...
Registering hooks...
Done!

**Comment by meteormatt** [comment]
@omidfi Oh. Maybe it works on 10.10.2, but not works after 10.10.4

**Comment by matteoacrossi** [comment]
@meteormatt I will investigate the issue on my configuration. As a workaround you can cd to the directory of the script and issue the commands with sudo manually

**Comment by albacoretuna** [comment]
Today I just heard the stupid sound again :( Even though it was working for a week!

**Comment by matteoacrossi** [comment]
@omidfi did anything change in your system? Did you update to 10.10.5?

**Comment by dajare** [comment]
I have updated to 10.10.5 on MacBook (Early 2015). Before the update I'm certain `nobootsound` was working fine. Now ... I'm not sure. Mostly not.

There is a variable - I realize I sometimes shutdown with my Grados (headphones) plugged in, but they'll be unplugged before next startup. It turns out (old news here I'm sure - but I'm new to the Mac world) that the system maintains [different volumes for headphones or speakers](http://apple.stackexchange.com/a/200349/136150). Could this be affecting the _apparently_ glitchy behaviour of `nobootsound`?

**Comment by albacoretuna** [comment]
@teored90 I think the head phones were doing it! 
Now that I keep them plugged in all the time, it works!

**Comment by meteormatt** [comment]
I found it works on 10.10.5 when I install it manually.
It is will be muted every time I login.

**Comment by matteoacrossi** [comment]
@omidfi OS X keeps different volumes for headphones and speakers, but I couldn't find a way to detect whether headphones are plugged in or not via AppleScript. This indeed poses a problem to the script functionality. I need to think about it... Unless someone knows how to detect programmatically if the headphones are plugged in.

@meteormatt I'm not sure if I understand. After manual installation the script works as expected or you have the audio muted after you log in, even if it was not muted before shutdown?

**Comment by meteormatt** [comment]
@teored90 Yes

**Comment by matteoacrossi** [comment]
@meteormatt Please try and install the latest version which includes some logging to the Console. You may want to try and clone the latest version of the script, install it and then try and restart the computer. In the Console, under All Messages, you should find two log entries if you filter for `nobootsound`.

**Comment by meteormatt** [comment]
The latest script still can not auto install.
After I install it manually.
It is muted every time I login, do not restore volume.

**Comment by matteoacrossi** [comment]
Check in the Console for messages with `nobootsound` in the text, in the All Messages category. You can use the filter on the top right of the window.
You should find these two lines

```
8/31/15 19:55:52.209 ffffff[1986]: Nobootsound. Volume muted before shutdown: false
8/31/15 19:59:25.196 _softwareupdate[200]: Nobootsound restoring volume to previous value. Mute: false
```

**Comment by meteormatt** [comment]
```
15/9/1 下午3:36:32.162 Meteor[405]: Nobootsound. Volume muted before shutdown: false
15/9/1 下午3:36:52.223 _mdnsresponder[222]: Nobootsound restoring volume to previous value. Mute: false
15/9/1 下午6:04:06.938 Meteor[6397]: Nobootsound. Volume muted before shutdown: true
15/9/2 上午10:24:12.379 _softwareupdate[222]: Nobootsound restoring volume to previous value. Mute: true
```

**Comment by matteoacrossi** [comment]
The script is executed as expected at boot and at logout. Are you using headphones or external audio devices?

**Comment by meteormatt** [comment]
No

**Comment by matteoacrossi** [comment]
I notice that in the second log entry the volume was muted even before shutdown. So it is expected that the volume is muted after login. Please make sure that the problematic behavior appears if the volume is not muted before shutdown. Anyway, I'm running out of ideas for possible solutions

**Comment by meteormatt** [comment]
```
15/9/6 上午9:26:57.080 _softwareupdate[222]: Nobootsound restoring volume to previous value. Mute: false
15/9/6 上午9:34:48.778 Meteor[445]: Nobootsound. Volume muted before shutdown: false
15/9/6 上午9:35:05.123 _mdnsresponder[222]: Nobootsound restoring volume to previous value. Mute: false
```

I do not mute the volume before reboot. But it is muted when I login the system.

**Comment by ghost** [comment]
I have also have the boot sound after installing the scripts and it seems that my external usb soundcard is causing the problems. 

Since this external card doesn't have a mute function, the script doesnt work, however, if I disconnect the soundcard, then mute my onboard audio, everything is fine. 

Is there a way to mute the onboard even if there is an external soundcard connected?

OSX 10.11.2

**Comment by matteoacrossi** [comment]
Hi noreye,

To my knowledge, it is not possible to mute selectively an audio device
using apple script. Only the output device in use can be muted. I will give
a look around to see if there is a way to make it work.

Il giorno dom 17 gen 2016, 16:04 noreye notifications@github.com ha
scritto:

**Comment by ghost** [comment]
Thanks. Maybe a work around could be muting the onboard audio when a new soundcard is detected? although, I dont know if that is possible in apple script.

**Comment by matteoacrossi** [comment]
Unfortunately neither of the two things seems to be possible using AppleScript in a clean way. A possibility could be using a third party command line utility, but this increases the complexity of the script. I found an utility that allows to switch audio devices buy requires Xcode command line tools, which the average user doesn’t need.

On 17 January 2016 at 16:42:54, noreye (notifications@github.com) wrote:

Thanks. Maybe a work around could be muting the onboard audio when a new soundcard is detected? although, I dont know if that is possible in apple script.

**Comment by ghost** [comment]
Thanks for looking. Since I know what the problem is, I will just have to remember to mute my onboard audio before plugging in my device. 

BTW - really appreciate you sharing this script and keeping active here :)

**Comment by ron-t** [comment]
Hello,

I too was getting the boot sound after installing the script. I'm using OSX 10.11.3 on a mid-2015 rMBP.
The problem turned out to be that nobootsound_logoutvol had "-e false" written to it instead of just "false".
I removed the "Bash version check for 'echo'" lines in the script (to avoid any use of echo -e) and that solved the problem. 

My (potentially flawed) rationale: Running "echo -e" in sh shows that it's not a valid option; "-e" is printed.

**Comment by matteoacrossi** [comment]
Dear @ron-t, thanks for reporting this problem, which has been introduced in Pull #4 , by user @dzogrim.   Anyway, please file a new Issue so that your problem can be solved independently, since the origin of the problem is already clear.

Thank you very much for your help!

**Comment by dzogrim** [comment]
@ron-t yes… OS X 'echo' still doesn't support "-e" sequences.
Should really double check wich version of 'echo' is installed and found at first, after bash check… my bad. Something like use "-e" when GNU version is found, don't use it when BSD version is…
Or install GNU 'echo' with [Mac Ports](https://www.macports.org/install.php):
`sudo port install coreutils bash` to get better tools…
