### ISSUE TITLE
It does not restore the value after login

### ISSUE THREAD

**Issue by sashabeep** [teored90/nobootsound#3]
BUT anyway, it mutes sound before reboot, so it's work for me. I can unmute it by myself

10.10.5
MBA Mid 13

**Comment by matteoacrossi** [comment]
Dear @sashabeep please open a terminal and check the output of

```
cat .nobootsound_logoutvol
```

**Comment by sashabeep** [comment]
```
murzic:~ sashabeep$ cat .nobootsound_logoutvol
false
```

**Comment by matteoacrossi** [comment]
Could you please execute the two commands below and test it?

```
sudo defaults write com.apple.loginwindow LoginHook  ~/.nobootsound_loginhook
sudo defaults write com.apple.loginwindow LogoutHook ~/.nobootsound_logouthook
```

**Comment by sashabeep** [comment]
Still false after that, muted by default on reboot

**Comment by matteoacrossi** [comment]
What if you execute manually the following commands (after having muted the volume manually)

```
read val < ~/.nobootsound_logoutvol
osascript -e "if not $val then set volume without output muted"
```

Also, please notice that if you mute the volume by repeatedly pressing the volume down button then this command does not work, because to the operative system the volume is not muted but set to zero.

**Comment by sashabeep** [comment]
Strange. Manually it works

**Comment by matteoacrossi** [comment]
Ok, now I would like you to paste the output of

```
ls -la ~/.noboot*
```

Thank you very much for your fast responses!

**Comment by sashabeep** [comment]
```
murzic:~ sashabeep$ ls -la ~/.noboot*
-rwxr-xr-x@ 1 sashabeep  staff  216 25 авг 23:22 /Users/sashabeep/.nobootsound_loginhook
-rwxr-xr-x@ 1 sashabeep  staff  241 25 авг 23:22 /Users/sashabeep/.nobootsound_logouthook
-rw-r--r--  1 sashabeep  staff    6 25 авг 23:22 /Users/sashabeep/.nobootsound_logoutvol
```

**Comment by matteoacrossi** [comment]
This is strange. The file permissions are fine. I'm wondering if there is some change in OS X 10.10.5, maybe due to the security fix for DLYD. I haven't updated my computer yet. I will try next week and will hopefully come back to you with a fix for this problem.

**Comment by matteoacrossi** [comment]
I updated my OS to 10.10.5 and tested the script and it works as expected. In the latest version I added a couple of lines for logging to the Console. You may want to try and clone the latest version of the script, install it and then try and restart the computer. In the Console, under All Messages, you should find two log entries if you filter for `nobootsound`.
