### ISSUE TITLE
-e option used in echo which is unsupported in BSD version of echo

### ISSUE THREAD

**Issue by ron-t** [teored90/nobootsound#6]
Originally described here: https://github.com/teored90/nobootsound/issues/2#issuecomment-196958012
I was getting the boot sound after installing the script. I'm using OSX 10.11.3 on a mid-2015 rMBP.
The problem turned out to be that nobootsound_logoutvol had "-e false" written to it instead of just "false".
I removed the "Bash version check for 'echo'" lines in the script (to avoid any use of echo -e) and that solved the problem.

According to @teored90 (https://github.com/teored90/nobootsound/issues/2#issuecomment-196968846) this is an issue introduced in Pull #4 .

**Comment by dzogrim** [comment]
Maybe a better [solution](http://wiki.bash-hackers.org/commands/builtin/printf#replacement_echo) is to use `printf` in place of `echo`.

**Comment by matteoacrossi** [comment]
I removed the code "Bash version check for 'echo'" in commit a8cf71f. This should work for most users. I will look at the `printf` solution. Does it come with OSX by default?

**Comment by dzogrim** [comment]
@teored90 yes, as I remember, I think so : https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/printf.1.html

**Comment by matteoacrossi** [comment]
I replaced echo with `printf`. I tested the install script and it worked flawlessly on my computer.
