### ISSUE TITLE
No work

### ISSUE THREAD

**Issue by usego1** [teored90/nobootsound#8]
Does not work on my Imac 2015!

but fund else where in the net open Terminal : Type whit your PW 

sudo nvram SystemAudioVolume=%80

and now its SILENCE !!  Thanks ! God
greets Jarre

**Comment by matteoacrossi** [comment]
Dear usego1,
could you please help me diagnose the bug? Can you please copy the output of the command  `ls -la /Library/LogHook`?

**Comment by usego1** [comment]
here the output : 

```
total 24
drwxr-xr-x   5 root  wheel   170 30 Mär 16:09 .
drwxr-xr-x+ 65 root  wheel  2210 30 Mär 17:04 ..
-rwxr-xr-x@  1 root  wheel   332 30 Mär 16:09 nobootsound_loginhook
-rwxr-xr-x@  1 root  wheel   372 30 Mär 16:09 nobootsound_logouthook
-rw-r--r--   1 root  wheel     5 31 Mär 17:58 nobootsound_logoutvol
```

**Comment by matteoacrossi** [comment]
OK, the files look good in the directory. Please try to enter these two commands

```
sudo defaults write com.apple.loginwindow LoginHook  /Library/LogHook/loginhook
sudo defaults write com.apple.loginwindow LogoutHook  /Library/LogHook/logouthook
```

**Comment by usego1** [comment]
These Command does not give any output !

**Comment by matteoacrossi** [comment]
Yes, that's correct. I'm sorry. I should have said that.
You should now try to restart the PC and check whether the sound plays out or not. Please make sure that your sound is not unmuted before shutting down and after login. Please also make sure that you don't have headphones plugged in.

Thank you!

**Comment by usego1** [comment]
No Sound on restart ! i think is becouse i have the nvram command wirten ealier!now i have silence !
just a simple Command in terminal and silence !
